# 🏷️ Named Entity Recognition (NER) with NLTK

## 📌 What is Named Entity Recognition?

**Named Entity Recognition (NER)** is an NLP technique used to identify and classify important real-world entities present in text.

NER can recognize entities such as:

| Entity Type | Example |
|---|---|
| 👤 Person | `Gustave Eiffel` |
| 🌍 Location | `India`, `Paris` |
| 🏢 Organization | `Google`, `Microsoft` |
| 📅 Date | `24 September 1989` |
| ⏰ Time | `4:30 PM` |
| 💰 Money | `$1 million` |
| 📊 Percentage | `20%` |
| 🌐 Geopolitical Entity | `France`, `India` |

### Example

**Input:**

`Gustave Eiffel designed the Eiffel Tower in France.`

NER attempts to identify entities such as:

`Gustave Eiffel → PERSON`

`France → GPE`

---

# 🔄 NER Pipeline in NLTK

The traditional NLTK NER pipeline follows these steps:

**Raw Text**

⬇️

**Word Tokenization**

⬇️

**POS Tagging**

⬇️

**Named Entity Chunking**

⬇️

**Named Entities**

### In Short

`Text → Tokens → POS Tags → NER Chunking → Entities`

In [1]:
import nltk

from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag
from nltk.chunk import ne_chunk


# Download required NLTK resources
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("averaged_perceptron_tagger_eng")
nltk.download("maxent_ne_chunker_tab")
nltk.download("words")

[nltk_data] Downloading package punkt to /Users/milind/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/milind/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/milind/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]     /Users/milind/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker_tab.zip.
[nltk_data] Downloading package words to /Users/milind/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.


True

# 📝 Example Text

We will perform Named Entity Recognition on the following sentence:

`The Eiffel Tower was built from 1887 to 1889 by French engineer Gustave Eiffel, whose company specialized in building metal frameworks and structures.`

The main objective is to automatically identify named entities such as **people, locations, organizations, and geopolitical entities**.

In [2]:
# Example sentence
sentence = (
    "The Eiffel Tower was built from 1887 to 1889 by French engineer "
    "Gustave Eiffel, whose company specialized in building metal "
    "frameworks and structures."
)

print(sentence)

The Eiffel Tower was built from 1887 to 1889 by French engineer Gustave Eiffel, whose company specialized in building metal frameworks and structures.


# 1️⃣ Step 1: Word Tokenization

Before performing NER, the sentence must first be divided into individual tokens.

The process is:

**Raw Sentence → Individual Tokens**

Punctuation marks may also be treated as separate tokens.

In [3]:
# Convert the sentence into individual tokens
tokens = word_tokenize(sentence)

print("Tokens:")
print(tokens)

Tokens:
['The', 'Eiffel', 'Tower', 'was', 'built', 'from', '1887', 'to', '1889', 'by', 'French', 'engineer', 'Gustave', 'Eiffel', ',', 'whose', 'company', 'specialized', 'in', 'building', 'metal', 'frameworks', 'and', 'structures', '.']


# 2️⃣ Step 2: Part-of-Speech (POS) Tagging

NER uses grammatical information to help understand the role of each word.

After tokenization, `pos_tag()` assigns a **Penn Treebank POS tag** to every token.

For example:

`Gustave → NNP`

`Eiffel → NNP`

Proper nouns such as `Gustave Eiffel` are important candidates for named entities.

In [4]:
# Assign a Part-of-Speech tag to each token
pos_tags = pos_tag(tokens)

print("POS-Tagged Tokens:")

for word, tag in pos_tags:
    print(f"{word:<15} ---> {tag}")

POS-Tagged Tokens:
The             ---> DT
Eiffel          ---> NNP
Tower           ---> NNP
was             ---> VBD
built           ---> VBN
from            ---> IN
1887            ---> CD
to              ---> TO
1889            ---> CD
by              ---> IN
French          ---> JJ
engineer        ---> NN
Gustave         ---> NNP
Eiffel          ---> NNP
,               ---> ,
whose           ---> WP$
company         ---> NN
specialized     ---> VBD
in              ---> IN
building        ---> NN
metal           ---> NN
frameworks      ---> NNS
and             ---> CC
structures      ---> NNS
.               ---> .


# 3️⃣ Step 3: Named Entity Chunking

After POS tagging, `ne_chunk()` analyzes the tagged words and groups related tokens into **named entity chunks**.

For example:

`Gustave` + `Eiffel`

may be grouped as:

`PERSON → Gustave Eiffel`

This process is known as **chunking** because multiple related tokens can be combined into one meaningful entity.

In [5]:
# Perform Named Entity Recognition
ner_tree = ne_chunk(pos_tags)

# Display the NER tree as text
print(ner_tree)

(S
  The/DT
  (ORGANIZATION Eiffel/NNP Tower/NNP)
  was/VBD
  built/VBN
  from/IN
  1887/CD
  to/TO
  1889/CD
  by/IN
  (GPE French/JJ)
  engineer/NN
  (PERSON Gustave/NNP Eiffel/NNP)
  ,/,
  whose/WP$
  company/NN
  specialized/VBD
  in/IN
  building/NN
  metal/NN
  frameworks/NNS
  and/CC
  structures/NNS
  ./.)


# 4️⃣ Extract Named Entities Programmatically

The output of `ne_chunk()` is a tree structure.

Instead of only displaying the tree, we can extract each detected entity into a simple and readable format:

`Entity → Entity Type`

This is more practical when the extracted entities need to be stored, analyzed, or used in another NLP pipeline.

In [6]:
# Store extracted named entities
named_entities = []


for chunk in ner_tree:

    # Named entities are represented as subtrees
    if hasattr(chunk, "label"):

        # Combine multiple words belonging to the same entity
        entity = " ".join(
            word for word, tag in chunk.leaves()
        )

        # Get the entity category
        entity_type = chunk.label()

        # Store the result
        named_entities.append((entity, entity_type))


# Display extracted entities
print("Named Entities:")
print("-" * 40)

for entity, entity_type in named_entities:
    print(f"{entity:<25} ---> {entity_type}")

Named Entities:
----------------------------------------
Eiffel Tower              ---> ORGANIZATION
French                    ---> GPE
Gustave Eiffel            ---> PERSON


# 🌳 Understanding the NER Tree

NLTK's `ne_chunk()` returns a tree containing normal POS-tagged words and detected named entities.

A simplified output may look like:

`(PERSON Gustave/NNP Eiffel/NNP)`

This means:

`Gustave Eiffel → PERSON`

The entity label appears first, followed by the words belonging to that entity.

---

# 📚 Common NLTK Named Entity Labels

| NER Label | Meaning | Example |
|---|---|---|
| `PERSON` | Person | `Gustave Eiffel` |
| `ORGANIZATION` | Company, institution, or organization | `Google` |
| `GPE` | Geopolitical Entity | `India`, `France` |
| `LOCATION` | Geographical location | Region or place |
| `FACILITY` | Building or facility | Airport, bridge, monument |
| `GSP` | Geopolitical or social group | Context-dependent |

## 📌 What is `GPE`?

`GPE` stands for **Geopolitical Entity**.

It generally represents geographical locations that also have political or administrative boundaries.

Examples:

`India → GPE`

`France → GPE`

`Mumbai → GPE`

---

# ⚠️ Important Limitation of NLTK NER

NLTK's `ne_chunk()` is a traditional named entity recognizer and supports a relatively limited set of entity categories.

It may not reliably detect categories such as:

- Dates
- Times
- Money
- Percentages
- Products
- Events

For example, values such as `1887` and `1889` may not automatically be classified as `DATE` entities by NLTK's standard `ne_chunk()` model.

Modern NLP libraries and transformer-based NER models generally provide broader and more accurate entity recognition.

# 🛠️ Reusable NER Function

For practical use, the complete NER pipeline can be placed inside a reusable function.

The function performs:

**Text → Tokenization → POS Tagging → NER → Entity Extraction**

It returns the detected entities as a structured list.

In [8]:
def extract_named_entities(text):
    """
    Extract named entities from the given text using NLTK.

    Parameters
    ----------
    text : str
        Input text from which named entities will be extracted.

    Returns
    -------
    list of tuples
        Each tuple contains:
        (entity_text, entity_type)
    """

    # Step 1: Tokenize the input text
    tokens = word_tokenize(text)

    # Step 2: Assign POS tags
    pos_tags = pos_tag(tokens)

    # Step 3: Perform Named Entity Recognition
    ner_tree = ne_chunk(pos_tags)

    # Step 4: Extract entities from the NER tree
    entities = []

    for chunk in ner_tree:

        if hasattr(chunk, "label"):

            # Combine words belonging to the same entity
            entity_text = " ".join(
                word for word, tag in chunk.leaves()
            )

            # Get the entity category
            entity_type = chunk.label()

            entities.append(
                (entity_text, entity_type)
            )

    return entities

In [9]:
# Extract named entities
entities = extract_named_entities(sentence)


# Display the results
print("Detected Named Entities")
print("=" * 50)

for entity, entity_type in entities:
    print(f"{entity:<30} {entity_type}")

Detected Named Entities
Eiffel Tower                   ORGANIZATION
French                         GPE
Gustave Eiffel                 PERSON


# 🧠 Key Takeaways

- **Named Entity Recognition (NER)** identifies important real-world entities in text.
- `word_tokenize()` divides text into individual tokens.
- `pos_tag()` identifies the grammatical role of each token.
- `ne_chunk()` uses POS-tagged tokens to detect named entities.
- NLTK represents detected entities as tree structures.
- Multi-word entities such as `Gustave Eiffel` can be grouped into a single entity.
- Entity labels include categories such as `PERSON`, `ORGANIZATION`, and `GPE`.
- Extracting entities programmatically is more practical than relying only on `.draw()`.
- NLTK's built-in NER is useful for learning traditional NLP, but modern NER systems generally support more entity types and better contextual understanding.

# 🏆 Complete NER Pipeline

**Raw Text**

⬇️

**Word Tokenization**

⬇️

**POS Tagging**

⬇️

**Named Entity Chunking**

⬇️

**Entity Extraction**

⬇️

**Structured Named Entities**

### In Short

`Raw Text → Tokens → POS Tags → NER Tree → Extracted Entities`